### ISSUE TITLE
Main.js configuration

### ISSUE THREAD

**Issue by RobineSavert** [dvuckovic/vue3-bootstrap-icons#7]
According to the readme file, the package should be imported in the main.js and used. This is what we have done in our project. But now everytime the whole bootstrap-icon.svg is loaded.

Your answer in https://github.com/dvuckovic/vue3-bootstrap-icons/issues/5 says it is wrongly imported in the Vite config. How should your package be configured in the Vite config? As we have the same issue.

Our main.js file looks like this:

```
`import { createApp } from 'vue'
import { createPinia } from 'pinia'
import piniaPersist from 'pinia-plugin-persist'
import App from './App.vue'
import router from './router/router'
import i18n from './i18n'
import "bootstrap"
import BootstrapIcon from '@dvuckovic/vue3-bootstrap-icons';
import Spinner from '@/components/Spinner'
import "@/assets/scss/styles.scss";

const pinia = createPinia()
pinia.use(piniaPersist)

const app = createApp(App)

window.onunhandledrejection = function(errorEvent) {
  console.error(errorEvent);
  
  var errorStatus = errorEvent["reason"]["status"]

  if(errorStatus === 401) {
    router.push({ name: 'login' })
  }

  return false;
}

app.use(i18n)
app.use(router)
app.use(pinia)

app.component('BootstrapIcon', BootstrapIcon);
app.component('Spinner', Spinner)
app.mount('#app')`
```

We have nothing in the Vite config file for the icons.. Should we? If so, how?

**Comment by dvuckovic** [comment]
From the description of this repo:

> A Vue.js component for rendering [Bootstrap Icons](https://icons.getbootstrap.com/) via the SVG sprite method.

Where _SVG sprite method_ means that the complete `bootstrap-icon.svg` will be loaded once for the whole app, and then the icon component will render the specific icons by referring to a particular area (sprite) of the big image via its identifier.

Can you confirm that `bootstrap-icon.svg` resource is loaded only once for app?

**Comment by RobineSavert** [comment]
Thanks for your reply!

With our current setup, the bootstrap-icon.svg is loaded everytime we use < BootstrapIcon  icon = " send-fill "  / > somewhere..

**Comment by 1Saurus2Saurus** [comment]
@dvuckovic Is there already a fix for this issue?
![image](https://github.com/dvuckovic/vue3-bootstrap-icons/assets/153267494/a860efbd-84df-49fd-8d01-102409f8ebab)

Every time something is conditionally loaded, it loads the whole SVG again

**Comment by RobineSavert** [comment]
Is there any news about this?

**Comment by dvuckovic** [comment]
Yes, sorry for the late answer, this is just a pet project.

I can acknowledge that the usage of the component in its current iteration is a bit clunky and results in multiple requests. This might not be a deal-breaker in smaller single-page apps (my only use case so far), but for anything larger, the approach would need to be changed, so the sprites are injected only once per app and then simply referenced.

I'm in the process of preparing [a PR](https://github.com/dvuckovic/vue3-bootstrap-icons/pull/8) with the new approach. I hit a snag with some typing issues, and I'm currently trying to resolve them. But this should not prevent you, should you wish so, to give it a try via a local checkout and report back if it works as expected. Instructions in the PR's README contain a code example for injecting sprites once per app, and the component can be put into this mode as described (it will not automatically load anything).

```ts
import { createApp } from 'vue'
import App from './App.vue'
import { BootstrapIcon } from '@dvuckovic/vue3-bootstrap-icons'
import { injectBootstrapIcons } from '@dvuckovic/vue3-bootstrap-icons/utils'
import BootstrapIcons from 'bootstrap-icons/bootstrap-icons.svg?raw'
import '@dvuckovic/vue3-bootstrap-icons/dist/style.css'

injectBootstrapIcons(BootstrapIcons)

const app = createApp(App)

app.component('BootstrapIcon', BootstrapIcon)

app.mount('#app')
```

> EDIT: Drop obsolete prop, this is now the preferred way of using the component.

**Comment by RobineSavert** [comment]
Thank you so much for taking the time to look at this issue and making it work for us. I will try to implement your changes & report back accordingly. Thanks again!

**Comment by RobineSavert** [comment]
Hi, I checked your PR locally with multiple routes and child components and everything seems to be working fine. Can you please merge it and push it so we can use it in our project? Thanks again!

**Comment by dvuckovic** [comment]
[v2.0.0](https://github.com/dvuckovic/vue3-bootstrap-icons/releases/tag/v2.0.0) was published on NPM. I did have a last minute change to remove the prop, injecting sprites is now mandatory as this approach makes much more sense. README will have the latest setup instructions, but I will adjust it in my comment above too.

Thanks for the report & testing!
